add --watch flag for auto rebuild when emulating

diff --git a/emulate b/emulate
--- a/emulate
+++ b/emulate
@@ -3,6 +3,7 @@
 filename=''
 window_scale=1
 print_help=0
+watch=0
 
 for i in "$@"; do
     case "$i" in
@@ -16,6 +17,9 @@ for i in "$@"; do
             ;;
         --scale=*)
             window_scale="${i#*=}"
+            ;;
+        --watch)
+            watch=1
             ;;
         --help) print_help=1 ;;
         *)
@@ -34,16 +38,90 @@ if [ -z "$filename" ] || [ "$print_help" == 1 ]; then
     echo "Flags:" >&2
     echo "  --clean         | Remove build files and exit." >&2
     echo "  --scale=[SCALE] | Scale the window by an integer amount." >&2
+    echo "  --watch         | Watch for source changes, automatically rebuilding when a change is detected." >&2
     echo "  --help          | Display this message." >&2
     echo "To remove build files, run" >&2
     echo "  $0 --clean" >&2
     exit "$([ "$print_help" == 1 ])"
 fi
 
+build() {
+    rsync "$filename" emu/ino.cpp -u || return 1
+    rsync -a src emu/ -u || return 1
+    make -C emu WINDOW_SCALE="$window_scale" || return 1
+    return 0
+}
 
+if [ $watch == 0 ]; then
+    build || exit 1
+    emu/ino
+    exit $?
+fi
 
-rsync "$1" emu/ino.cpp -u || exit 1
-rsync -a src emu/ -u || exit 1
-make -C emu WINDOW_SCALE="$window_scale" || exit 1
+poll_src_changes() {
+    inotifywait -m -r -q --format '%w%f' -e CLOSE_WRITE "$filename" src/ --include '.*\.(hpp|cpp|h)$' | while read -r file; do
+        rsync "$file" emu/"$file" -u
+    done
+}
 
-emu/ino || exit 1
+poll_src_changes2() {
+    inotifywait -m -q --format '%w%f' -e CLOSE_WRITE "$filename" | while read -r file; do
+        rsync "$file" emu/ino.cpp -u
+    done
+}
+
+pidfile=$(mktemp)
+buildfile=$(mktemp)
+
+__exit() {
+    rm "$pidfile" "$buildfile"
+    pkill -P "$$" &>/dev/null
+    kill "$$"
+    exit 0
+}
+ 
+trap __exit INT
+
+poll_build_changes() {
+    inotifywait -m -r -q emu/ -e MOVED_TO --include '.*\.(hpp|cpp|h)$' | while read -r file; do
+        echo 1 > "$buildfile"
+    done
+}
+
+# If watching, don't exit when build fails, just keep watching.
+build
+poll_src_changes &
+poll_src_changes2 &
+poll_build_changes &
+
+echo '' > "$pidfile"
+echo 1 > "$buildfile"
+
+while true; do
+    sleep 0.5
+    read -r buildflag < "$buildfile"
+    read -r pid < "$pidfile"
+    if [ "$buildflag" == 1 ]; then
+        sleep 0.5
+        
+        if make -C emu WINDOW_SCALE="$window_scale"; then
+            if [ ! -z "$pid" ]; then
+                echo ">>$pid<<"
+                kill "$pid"
+                wait "$pid"
+                echo '' > "$pidfile"
+            fi
+
+            cp emu/ino emu/ino.watch
+            ./emu/ino.watch &
+            pid=$!
+            echo "$pid" > "$pidfile"
+        fi
+
+        echo 0 > "$buildfile"
+    elif [ ! -z "$pid" ] && ! ps -p "$pid" >/dev/null; then
+        __exit
+    fi
+done
+
+wait
